# Generated by Django 4.2.1 on 2023-06-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_auto_20180830_1759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
