# Generated by Django 4.2.1 on 2023-06-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_alter_articlepost_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="articlepost", name="updated",),
    ]
