# Generated by Django 4.2.1 on 2023-06-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0004_remove_articlepost_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="article_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
