# Generated by Django 4.2.1 on 2023-06-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_articlepost_article_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="articlepost", name="article_id",),
    ]
